/**
 * Pure-TypeScript port of ``eopx.vault.enroll.enroll_from_card``.
 *
 * Running the enrollment derivation **client-side** means the backend
 * never learns ``device_entropy`` nor any of the derived secrets
 * (``device_secret``, ``enrollment_fp``, ``public_tag``). The PWA only
 * uploads the photographed image to ``/api/v1/extract`` and receives the
 * 91 public symbols + card fingerprint in return. Everything else stays
 * on the device.
 *
 * Parity with the Python implementation is guaranteed by the test
 * vectors in ``__tests__/vectors.json`` (generated by
 * ``scripts/gen_test_vectors.py``).
 */

import { cardFingerprint, concat, hkdfSha3_512, toHex } from "./crypto";

const utf8 = (s: string): Uint8Array => new TextEncoder().encode(s);

// Domain-separation tags — MUST match Python ``eopx.vault.enroll``.
export const INFO_SHADOW = utf8("esoptron.enroll.shadow_hologram.v1");
export const INFO_IDPRIV = utf8("esoptron.enroll.identity.private.v1");
export const INFO_IDPUBTAG = utf8("esoptron.enroll.identity.public_tag.v1");
export const INFO_ENROLLFP = utf8("esoptron.enroll.fingerprint.v1");

export const DEVICE_ENTROPY_BYTES = 32;
export const PUBLIC_TAG_BYTES = 16;
export const SHADOW_BYTES = 64;
export const FP_BYTES = 32;

export interface EnrollmentRecord {
  /** Shared fingerprint of the issuing vault (= card_fingerprint). */
  vaultFp: Uint8Array;
  /** SENSITIVE — never leaves the device. Use for delegation flows. */
  deviceSecret: Uint8Array;
  /** Unique per enrollment, links (vault, device) without revealing either. */
  enrollmentFp: Uint8Array;
  /** Public 16-byte tag, safe to publish. */
  publicTag: Uint8Array;
  /** 64-byte seed for local hologram rendering. */
  shadowHologram: Uint8Array;
}

export interface EnrollmentRecordHex {
  vault_fp_hex: string;
  device_secret_hex: string;
  enrollment_fp_hex: string;
  public_tag_hex: string;
  shadow_hologram_hex: string;
}

/** Derive a per-device shadow hologram seed. */
export function deriveShadowHologram(
  cardFp: Uint8Array,
  deviceEntropy: Uint8Array,
  length: number = SHADOW_BYTES,
): Uint8Array {
  if (cardFp.length !== FP_BYTES)
    throw new Error(`card_fp must be ${FP_BYTES} bytes`);
  if (deviceEntropy.length !== DEVICE_ENTROPY_BYTES)
    throw new Error(`device_entropy must be ${DEVICE_ENTROPY_BYTES} bytes`);
  const ikm = concat(cardFp, deviceEntropy);
  return hkdfSha3_512(ikm, new Uint8Array(0), INFO_SHADOW, length);
}

/**
 * Run the enrollment ceremony from a freshly scanned PUBLIC card.
 *
 * Mirrors ``eopx.vault.enroll.enroll_from_card`` byte-for-byte. The
 * caller MUST provide ``deviceEntropy`` (32 bytes from
 * ``crypto.getRandomValues`` on the PWA, or reconstructed from a BIP-39
 * mnemonic when recovering).
 */
export function enrollFromCard(
  cardSymbols: ReadonlyArray<number>,
  deviceEntropy: Uint8Array,
): EnrollmentRecord {
  if (cardSymbols.length !== 91)
    throw new Error("card_symbols must have length 91");
  if (deviceEntropy.length !== DEVICE_ENTROPY_BYTES)
    throw new Error(`device_entropy must be ${DEVICE_ENTROPY_BYTES} bytes`);

  const fp = cardFingerprint(cardSymbols);

  // device_secret = HKDF-SHA3-512(ikm=device_entropy, salt=b"", info=INFO_IDPRIV, length=32)
  const deviceSecret = hkdfSha3_512(
    deviceEntropy, new Uint8Array(0), INFO_IDPRIV, 32,
  );
  // enrollment_fp = HKDF(ikm=device_secret, salt=fp, info=INFO_ENROLLFP, length=32)
  const enrollmentFp = hkdfSha3_512(
    deviceSecret, fp, INFO_ENROLLFP, 32,
  );
  // public_tag = HKDF(ikm=device_secret, salt=fp, info=INFO_IDPUBTAG, length=16)
  const publicTag = hkdfSha3_512(
    deviceSecret, fp, INFO_IDPUBTAG, PUBLIC_TAG_BYTES,
  );
  const shadow = deriveShadowHologram(fp, deviceEntropy);

  return {
    vaultFp: fp,
    deviceSecret,
    enrollmentFp,
    publicTag,
    shadowHologram: shadow,
  };
}

/** Hex-encoded view of an :class:`EnrollmentRecord` for storage / display. */
export function toHexRecord(rec: EnrollmentRecord): EnrollmentRecordHex {
  return {
    vault_fp_hex: toHex(rec.vaultFp),
    device_secret_hex: toHex(rec.deviceSecret),
    enrollment_fp_hex: toHex(rec.enrollmentFp),
    public_tag_hex: toHex(rec.publicTag),
    shadow_hologram_hex: toHex(rec.shadowHologram),
  };
}
