"""Compute SHA3-256 of an EPX-tracked document and write it to
``SPECS.SHA3-256``.

The document itself is never modified. The hash is computed on a
**normalised** representation of the file so that editor-induced
churn (BOM, CRLF, trailing whitespace, missing final newline) does
not invalidate the manifest. The raw bytes are still verified to be
valid UTF-8 — the manifest refuses to record a record for a file that
isn't decodable.

Normalisation steps (in order)::

    1. Refuse if the file is not valid UTF-8.
    2. Strip UTF-8 BOM (EF BB BF) if present.
    3. Normalise line endings to LF.
    4. Strip trailing whitespace from every line (ASCII space + tab).
    5. Ensure exactly one trailing LF.
    6. Apply Unicode NFC normalisation.

Hash format::

    sha3-256:<64-hex>

Manifest path: ``SPECS.SHA3-256`` at the repository root. The manifest
also tracks whitepapers and audit reports — anything the maintainer
chooses to sign. Use ``--all`` to refresh every doc currently in the
manifest in one pass, or ``--scan`` to bootstrap a manifest covering
all known signed-doc paths.

Usage::

    py tools/sign_spec.py docs/specs/EPX-2_card_v2.md
    py tools/sign_spec.py docs/specs/EPX-2_card_v2.md \\
        --key ~/.esoptron/jeremy.key.json
    py tools/sign_spec.py --all
    py tools/sign_spec.py --scan
"""

from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import sys
import unicodedata
from pathlib import Path
from typing import Dict, List, Optional

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from eopx.format.keys import EopxKey  # noqa: E402


MANIFEST = ROOT / "SPECS.SHA3-256"
HEADER = (
    "# EPX signed-document integrity manifest\n"
    "# Generated by tools/sign_spec.py. Hashes are computed on the\n"
    "# NORMALISED bytes of each file (UTF-8, no BOM, LF line endings,\n"
    "# stripped trailing whitespace, single final newline, Unicode NFC).\n"
    "# The raw on-disk file may differ from the hashed form by line\n"
    "# endings only; this is intentional so editors do not invalidate\n"
    "# the manifest by saving the file.\n"
    "#\n"
    "# Records are blank-line-separated. Format:  ``key: value``.\n"
    "#\n"
)

#: Default set of paths covered by --scan. Add new entries here when a
#: new spec / whitepaper / report should be tracked.
KNOWN_DOCS: tuple[str, ...] = (
    "docs/specs/EPX-2_card_v2.md",
    "docs/whitepaper_esoptron.md",
    "docs/whitepaper_metatron.md",
    "docs/whitepaper_metatron_mnemonic.md",
    "docs/whitepaper_metatron_separation.md",
    "docs/whitepaper_vault_protocols.md",
    "docs/migration_protocol.md",
    "docs/testing_guide.md",
    "docs/audit_report_2026-05-28.md",
    "docs/audit_report_2026-05-30.md",
    "docs/research_notes/yuga_lexicon_analysis.md",
    "RELEASE.md",
)


NORMALISATION_ID = "utf8+nobom+lf+striptrailws+finallf+nfc"


def normalise_bytes(raw: bytes) -> bytes:
    """Apply the normalisation pipeline. Raises on invalid UTF-8."""
    if raw.startswith(b"\xef\xbb\xbf"):
        raw = raw[3:]
    text = raw.decode("utf-8")
    # LF line endings.
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    # Strip trailing whitespace per line.
    lines = [ln.rstrip(" \t") for ln in text.split("\n")]
    text = "\n".join(lines)
    # Single trailing LF.
    text = text.rstrip("\n") + "\n"
    # NFC.
    text = unicodedata.normalize("NFC", text)
    return text.encode("utf-8")


def _parse(text: str) -> List[Dict[str, str]]:
    blocks: List[Dict[str, str]] = []
    current: Dict[str, str] = {}
    for line in text.splitlines():
        if line.startswith("#") or not line.strip():
            if current:
                blocks.append(current)
                current = {}
            continue
        if ":" not in line:
            continue
        k, _, v = line.partition(":")
        current[k.strip().lower()] = v.strip()
    if current:
        blocks.append(current)
    return blocks


def _format(blocks: List[Dict[str, str]]) -> str:
    out = [HEADER.rstrip("\n"), ""]
    keys = (
        "spec", "hash", "bytes-raw", "bytes-normalised",
        "normalisation", "author", "timestamp",
        "signer-pk-fp", "signature",
    )
    for blk in blocks:
        for k in keys:
            if k in blk:
                out.append(f"{(k + ':'):<18s} {blk[k]}")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def _sign_one(path: Path, *, author: str, timestamp: str,
              key: Optional[Path]) -> Dict[str, str]:
    if not path.is_file():
        raise SystemExit(f"document not found: {path}")
    raw = path.read_bytes()
    normalised = normalise_bytes(raw)
    digest_hex = hashlib.sha3_256(normalised).hexdigest()
    rel = path.resolve().relative_to(ROOT).as_posix()
    record: Dict[str, str] = {
        "spec": rel,
        "hash": f"sha3-256:{digest_hex}",
        "bytes-raw": str(len(raw)),
        "bytes-normalised": str(len(normalised)),
        "normalisation": NORMALISATION_ID,
        "author": author,
        "timestamp": timestamp,
    }
    if key is not None:
        deployment = EopxKey.load(key)
        if not deployment.has_secrets:
            raise SystemExit(f"key file has no secret material: {key}")
        signature = deployment.sign(hashlib.sha3_256(normalised).digest())
        signer_fp = hashlib.sha3_256(deployment.dilithium_pk).hexdigest()
        record["signer-pk-fp"] = f"sha3-256:{signer_fp}"
        record["signature"] = f"dilithium5:{signature.hex()}"
    return record


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("path", nargs="?", type=Path,
                    help="Document to (re)hash.")
    ap.add_argument("--author", default="Jérémy ZGONEC")
    ap.add_argument("--timestamp",
                    default=_dt.datetime.now(_dt.timezone.utc)
                    .strftime("%Y-%m-%dT%H:%M:%SZ"))
    ap.add_argument("--key", type=Path,
                    help="Path to JSON Dilithium-5 key.")
    ap.add_argument("--all", action="store_true",
                    help="Refresh every entry currently in the manifest.")
    ap.add_argument("--scan", action="store_true",
                    help="Bootstrap entries for every file in KNOWN_DOCS.")
    args = ap.parse_args()

    blocks: List[Dict[str, str]] = []
    if MANIFEST.exists():
        blocks = _parse(MANIFEST.read_text(encoding="utf-8"))

    targets: List[Path] = []
    if args.path is not None:
        targets.append(args.path)
    if args.all:
        for blk in blocks:
            p = ROOT / blk["spec"]
            if p not in targets:
                targets.append(p)
    if args.scan:
        for rel in KNOWN_DOCS:
            p = ROOT / rel
            if p.is_file() and p not in targets:
                targets.append(p)
    if not targets:
        ap.error("provide a path, or use --all / --scan")

    for tgt in targets:
        record = _sign_one(
            tgt, author=args.author, timestamp=args.timestamp, key=args.key,
        )
        replaced = False
        for i, blk in enumerate(blocks):
            if blk.get("spec") == record["spec"]:
                blocks[i] = record
                replaced = True
                break
        if not replaced:
            blocks.append(record)
        signed = "yes" if "signature" in record else "no"
        print(f"  + {record['spec']:<45s} {record['hash']} "
              f"raw={record['bytes-raw']} "
              f"normalised={record['bytes-normalised']} signed={signed}")

    # write_bytes to guarantee LF line endings on Windows (write_text would
    # promote \n to \r\n via the default newline= argument).
    MANIFEST.write_bytes(_format(blocks).encode("utf-8"))
    print(f"\nmanifest updated: {MANIFEST.name} "
          f"({len(blocks)} record(s), author={args.author!r}, "
          f"ts={args.timestamp})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
