/**
 * EPX-F §6 — Python ↔ TypeScript parity for the presentation layer.
 *
 * §9 tabulates the derivation, not the framing, so this half is pinned against
 * vectors generated by the Python implementation
 * (``py scripts/gen_figure_vectors.py``). Framing is where two ports drift
 * quietly: centring, padding, the caption separator. None of it is security —
 * and that is the reason to pin it, because nothing else would catch it.
 *
 * The rule the file enforces hardest is §6's: a **frozen** plate prints its
 * tag, a **living** plate prints none.
 */

import { describe, expect, it } from "vitest";

import vectors from "./figure_vectors.json";
import { fromHex } from "../crypto";
import {
  ASCII_RAMP,
  epochId,
  figureGrid,
  figureTag,
  renderRows,
} from "../artifactFigure";
import {
  UNICODE_RAMP,
  checkRamp,
  frames,
  gallery,
  livingPlate,
  livingRows,
  plate,
  plateSize,
} from "../figurePlate";

const utf8 = (s: string): Uint8Array => new TextEncoder().encode(s);

interface DerivationVec {
  name: string;
  merkle_root_hex: string;
  dilithium_pk_fp_hex: string;
  grid: number[][];
  canonical_text: string;
  figure_tag: string;
  epoch_id: string;
  ascii_rows: string[];
  unicode_rows: string[];
}

interface PresentationVec {
  name: string;
  plate_plain: string;
  plate_titled: string;
  plate_long_title: string;
  plate_ascii: string;
  plate_size_titled: [number, number];
}

interface LivingVec {
  state_utf8: string;
  activity: number;
  rows?: number[][];
  plate?: string;
  frames?: string[][];
}

const derivation = vectors.derivation as DerivationVec[];
const presentation = vectors.presentation as PresentationVec[];
const living = vectors.living as LivingVec[];

function gridOf(v: DerivationVec): number[][] {
  return figureGrid(fromHex(v.merkle_root_hex), fromHex(v.dilithium_pk_fp_hex));
}

describe("EPX-F ramps", () => {
  it("both ramps match the Python constants", () => {
    expect(ASCII_RAMP).toBe(vectors.ascii_ramp);
    expect(UNICODE_RAMP).toBe(vectors.unicode_ramp);
  });

  it("accepts the shipped ramps and explains why others fail", () => {
    expect(checkRamp(ASCII_RAMP)).toBeNull();
    expect(checkRamp(UNICODE_RAMP)).toBeNull();
    expect(checkRamp("abc")).toMatch(/16 glyphs/);
    // Sixteen glyphs, but two levels would look alike.
    expect(checkRamp("aabcdefghijklmno")).toMatch(/distinct/);
  });
});

describe("EPX-F derivation vectors (regenerated from Python)", () => {
  for (const v of derivation) {
    it(`${v.name}: grid, tag, epoch and both ramps agree`, () => {
      const grid = gridOf(v);
      expect(grid).toEqual(v.grid);
      expect(figureTag(grid)).toBe(v.figure_tag);
      expect(epochId(fromHex(v.dilithium_pk_fp_hex))).toBe(v.epoch_id);
      expect(renderRows(grid, ASCII_RAMP)).toEqual(v.ascii_rows);
      expect(renderRows(grid, UNICODE_RAMP)).toEqual(v.unicode_rows);
    });
  }
});

describe("EPX-F §6 — framed plates", () => {
  for (let i = 0; i < presentation.length; i += 1) {
    const p = presentation[i];
    const v = derivation[i];

    it(`${p.name}: an untitled plate frames exactly as Python does`, () => {
      expect(plate(gridOf(v))).toBe(p.plate_plain);
    });

    it(`${p.name}: title and epoch line up character for character`, () => {
      const grid = gridOf(v);
      expect(plate(grid, { title: "Relic", epoch: v.epoch_id })).toBe(
        p.plate_titled,
      );
    });

    it(`${p.name}: a caption wider than the grid widens the frame`, () => {
      // The case that catches a naive centring: the frame is sized by the
      // caption, so every grid row is re-centred inside it.
      const grid = gridOf(v);
      expect(
        plate(grid, {
          title: "a title far wider than sixteen cells",
          epoch: v.epoch_id,
        }),
      ).toBe(p.plate_long_title);
    });

    it(`${p.name}: the ASCII frame and ramp match`, () => {
      const grid = gridOf(v);
      expect(
        plate(grid, {
          title: "Relic",
          epoch: v.epoch_id,
          ramp: ASCII_RAMP,
          asciiFrame: true,
        }),
      ).toBe(p.plate_ascii);
    });

    it(`${p.name}: plateSize predicts what plate() actually draws`, () => {
      const grid = gridOf(v);
      const [w, h] = plateSize("Relic", v.epoch_id, figureTag(grid));
      expect([w, h]).toEqual(p.plate_size_titled);

      const drawn = plate(grid, {
        title: "Relic",
        epoch: v.epoch_id,
        ramp: ASCII_RAMP,
        asciiFrame: true,
      }).split("\n");
      expect(drawn).toHaveLength(h);
      for (const line of drawn) expect(Array.from(line)).toHaveLength(w);
    });
  }
});

describe("EPX-F §6 — a living face carries nothing to compare", () => {
  const base = derivation[0];

  for (const v of living) {
    if (v.rows === undefined) continue;
    it(`state ${JSON.stringify(v.state_utf8)} / activity ${v.activity}: drift matches Python`, () => {
      const grid = gridOf(base);
      expect(livingRows(grid, utf8(v.state_utf8), v.activity)).toEqual(v.rows);
      expect(
        livingPlate(grid, {
          stateBytes: utf8(v.state_utf8),
          activity: v.activity,
          epoch: base.epoch_id,
        }),
      ).toBe(v.plate);
    });
  }

  it("prints no tag, and says so with a dashed frame", () => {
    const grid = gridOf(base);
    const alive = livingPlate(grid, {
      stateBytes: utf8("block-900001"),
      activity: 3,
      epoch: base.epoch_id,
    });
    expect(alive).not.toContain(figureTag(grid));
    expect(alive).toContain("living");
    expect(alive).toContain("╌");

    const frozen = plate(grid, { title: "", epoch: base.epoch_id });
    expect(frozen).toContain(figureTag(grid));
    expect(frozen).toContain("─");
    expect(frozen).not.toContain("╌");
  });

  it("drift is capped, so a living face stays recognisably itself", () => {
    const grid = gridOf(base);
    const wild = livingRows(grid, utf8("block-900001"), 99);
    let moved = 0;
    for (let r = 0; r < grid.length; r += 1) {
      for (let c = 0; c < grid[r].length; c += 1) {
        if (wild[r][c] !== grid[r][c]) moved += 1;
      }
    }
    expect(moved).toBeLessThanOrEqual(5);
  });

  it("animation frames are reproducible from the ledger state", () => {
    const vec = living.find((v) => v.frames !== undefined);
    expect(vec).toBeDefined();
    const grid = gridOf(base);
    expect(frames(grid, utf8("animate"), 4, 5)).toEqual(vec!.frames);
  });
});

describe("EPX-F §6 — galleries", () => {
  it("lays plates side by side exactly as Python does", () => {
    const plates = derivation.map((v) =>
      plate(gridOf(v), {
        title: v.name,
        epoch: v.epoch_id,
        ramp: ASCII_RAMP,
        asciiFrame: true,
      }),
    );
    expect(plates).toEqual(vectors.gallery.plates);
    expect(gallery(plates)).toBe(vectors.gallery.rendered);
  });

  it("an empty gallery is empty, not a stray separator", () => {
    expect(gallery([])).toBe("");
  });
});
